# hpcagent_bench-autogen -- generated from tsvc_2_s1244_numpy.py; edit the numpy reference and regenerate, or delete this line to keep local edits as a hand override.
"""Auto-generated by NumpyToNumba (njit parallel=True). Decorator added; body preserved verbatim."""
import warnings
import numba as nb
from numba.core.errors import NumbaPerformanceWarning
warnings.filterwarnings('ignore', category=NumbaPerformanceWarning)
# Adapted from TSVC_2 -- Test Suite for Vectorizing Compilers (github.com/UoB-HPC/TSVC_2),
# NCSA/MIT license (UIUC). Reimplemented in NumPy as the HPCAgent-Bench correctness reference.
"""TSVC tsvc_2 kernel ``s1244`` (numpy reference)."""


@nb.njit(parallel=True, cache=True)
def s1244(a, b, c, d, LEN_1D):
    # array shapes (numpy->dace): a=(LEN_1D,), b=(LEN_1D,), c=(LEN_1D,), d=(LEN_1D,)
    for i in range(LEN_1D - 1):
        a[i] = b[i] + c[i] * c[i] + b[i] * b[i] + c[i]
        d[i] = a[i] + a[i + 1]
