# hpcagent_bench-autogen -- generated from comet_int4_gemm_numpy.py; edit the numpy reference and regenerate, or delete this line to keep local edits as a hand override.
"""Auto-generated by NumpyToNumba (njit parallel=True). Decorator added; body preserved verbatim."""
import warnings
import numba as nb
from numba.core.errors import NumbaPerformanceWarning
warnings.filterwarnings('ignore', category=NumbaPerformanceWarning)
import numpy as np

@nb.njit(parallel=True, cache=True)
def comet_int4_gemm(codes_left, codes_right, out):
    li1 = (codes_left & 1).astype(np.int32) + (codes_left >> 1 & 1).astype(np.int32)
    li0 = 2 - li1
    rj1 = (codes_right & 1).astype(np.int32) + (codes_right >> 1 & 1).astype(np.int32)
    rj0 = 2 - rj1
    __mmi0_b = rj0.T
    __mmi0_o = np.zeros((li0.shape[0], __mmi0_b.shape[1]), li0.dtype)
    for __mm0_i in nb.prange(li0.shape[0]):
        for __mm0_j in range(__mmi0_b.shape[1]):
            for __mm0_k in range(li0.shape[1]):
                __mmi0_o[__mm0_i, __mm0_j] += li0[__mm0_i, __mm0_k] * __mmi0_b[__mm0_k, __mm0_j]
    out[:, :, 0, 0] = __mmi0_o
    __mmi1_b = rj1.T
    __mmi1_o = np.zeros((li0.shape[0], __mmi1_b.shape[1]), li0.dtype)
    for __mm1_i in range(li0.shape[0]):
        for __mm1_j in range(__mmi1_b.shape[1]):
            for __mm1_k in range(li0.shape[1]):
                __mmi1_o[__mm1_i, __mm1_j] += li0[__mm1_i, __mm1_k] * __mmi1_b[__mm1_k, __mm1_j]
    out[:, :, 0, 1] = __mmi1_o
    __mmi2_b = rj0.T
    __mmi2_o = np.zeros((li1.shape[0], __mmi2_b.shape[1]), li1.dtype)
    for __mm2_i in range(li1.shape[0]):
        for __mm2_j in range(__mmi2_b.shape[1]):
            for __mm2_k in range(li1.shape[1]):
                __mmi2_o[__mm2_i, __mm2_j] += li1[__mm2_i, __mm2_k] * __mmi2_b[__mm2_k, __mm2_j]
    out[:, :, 1, 0] = __mmi2_o
    __mmi3_b = rj1.T
    __mmi3_o = np.zeros((li1.shape[0], __mmi3_b.shape[1]), li1.dtype)
    for __mm3_i in range(li1.shape[0]):
        for __mm3_j in range(__mmi3_b.shape[1]):
            for __mm3_k in range(li1.shape[1]):
                __mmi3_o[__mm3_i, __mm3_j] += li1[__mm3_i, __mm3_k] * __mmi3_b[__mm3_k, __mm3_j]
    out[:, :, 1, 1] = __mmi3_o