# hpcagent_bench-autogen -- generated from tsvc_2_s275_numpy.py; edit the numpy reference and regenerate, or delete this line to keep local edits as a hand override.
"""Auto-generated by NumpyToNumba (njit parallel=True). Decorator added; body preserved verbatim."""
import warnings
import numba as nb
from numba.core.errors import NumbaPerformanceWarning
warnings.filterwarnings('ignore', category=NumbaPerformanceWarning)
# Adapted from TSVC_2 -- Test Suite for Vectorizing Compilers (github.com/UoB-HPC/TSVC_2),
# NCSA/MIT license (UIUC). Reimplemented in NumPy as the HPCAgent-Bench correctness reference.
"""TSVC tsvc_2 kernel ``s275`` (numpy reference)."""


@nb.njit(parallel=True, cache=True)
def s275(aa, bb, cc, LEN_2D):
    # array shapes (numpy->dace): aa=(LEN_2D,LEN_2D), bb=(LEN_2D,LEN_2D), cc=(LEN_2D,LEN_2D)
    for i in nb.prange(LEN_2D):
        if aa[0, i] > 0.0:
            for j in range(1, LEN_2D):
                aa[j, i] = aa[j - 1, i] + bb[j, i] * cc[j, i]
